/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package luismendoza_examen1p2;

import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author luiscarlomendoza
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame_CRUD = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_PCadd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_IP1 = new javax.swing.JTextField();
        jTextField_Mascara1 = new javax.swing.JTextField();
        jTextField_HostName1 = new javax.swing.JTextField();
        jTextField_RAM = new javax.swing.JTextField();
        jTextField_CdA = new javax.swing.JTextField();
        jTextField_TdA = new javax.swing.JTextField();
        jButton_Guardar1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel_LabtopRemove = new javax.swing.JPanel();
        jLabel_IP2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_IP2 = new javax.swing.JTextField();
        jTextField_Mascara2 = new javax.swing.JTextField();
        jTextField_HostName2 = new javax.swing.JTextField();
        jTextField_Marca = new javax.swing.JTextField();
        jTextField_RdP = new javax.swing.JTextField();
        jButton_Guardar2 = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel_List = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel_Remove = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Quitar = new javax.swing.JTextField();
        jButtonRemove = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel_Principal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonIngresar = new javax.swing.JButton();
        jButtonCRUD = new javax.swing.JButton();

        jTabbedPane1.setBackground(new java.awt.Color(0, 204, 255));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel2.setText("IP");

        jLabel3.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel3.setText("Mascara");

        jLabel4.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel4.setText("Host Name");

        jLabel5.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel5.setText("RAM");

        jLabel6.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel6.setText("Capacidad de Almacenamiento");

        jLabel7.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel7.setText("Tipo de Almacenamiento");

        jLabel8.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel8.setText("Tarjeta Gráfica");

        jTextField_IP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IP1ActionPerformed(evt);
            }
        });

        jTextField_HostName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_HostName1ActionPerformed(evt);
            }
        });

        jButton_Guardar1.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jButton_Guardar1.setText("Guardar");
        jButton_Guardar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Guardar1MouseClicked(evt);
            }
        });
        jButton_Guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Guardar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_PCaddLayout = new javax.swing.GroupLayout(jPanel_PCadd);
        jPanel_PCadd.setLayout(jPanel_PCaddLayout);
        jPanel_PCaddLayout.setHorizontalGroup(
            jPanel_PCaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PCaddLayout.createSequentialGroup()
                .addGroup(jPanel_PCaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_PCaddLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_PCaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_PCaddLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_IP1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_PCaddLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Mascara1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_PCaddLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_CdA, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_PCaddLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_TdA, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_PCaddLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox1))
                            .addGroup(jPanel_PCaddLayout.createSequentialGroup()
                                .addGroup(jPanel_PCaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_PCaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_RAM, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_HostName1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel_PCaddLayout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(jButton_Guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(351, Short.MAX_VALUE))
        );
        jPanel_PCaddLayout.setVerticalGroup(
            jPanel_PCaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PCaddLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel_PCaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_IP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_PCaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Mascara1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_PCaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_HostName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_PCaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_RAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_PCaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_CdA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_PCaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_TdA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel_PCaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PC-Add", jPanel_PCadd);

        jLabel_IP2.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel_IP2.setText("IP");

        jLabel10.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel10.setText("Mascara");

        jLabel11.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel11.setText("Host Name");

        jLabel12.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel12.setText("Resolución de Pantalla");

        jLabel13.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel13.setText("RGB");

        jLabel14.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel14.setText("Marca");

        jButton_Guardar2.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jButton_Guardar2.setText("Guardar");
        jButton_Guardar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Guardar2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_LabtopRemoveLayout = new javax.swing.GroupLayout(jPanel_LabtopRemove);
        jPanel_LabtopRemove.setLayout(jPanel_LabtopRemoveLayout);
        jPanel_LabtopRemoveLayout.setHorizontalGroup(
            jPanel_LabtopRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LabtopRemoveLayout.createSequentialGroup()
                .addGroup(jPanel_LabtopRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_LabtopRemoveLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Mascara2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_LabtopRemoveLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_HostName2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel_LabtopRemoveLayout.createSequentialGroup()
                .addGroup(jPanel_LabtopRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_LabtopRemoveLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_LabtopRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_LabtopRemoveLayout.createSequentialGroup()
                                .addComponent(jLabel_IP2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_IP2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_LabtopRemoveLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox2))
                            .addGroup(jPanel_LabtopRemoveLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jTextField_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_LabtopRemoveLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_RdP, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel_LabtopRemoveLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jButton_Guardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(414, Short.MAX_VALUE))
        );
        jPanel_LabtopRemoveLayout.setVerticalGroup(
            jPanel_LabtopRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LabtopRemoveLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel_LabtopRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_IP2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_IP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_LabtopRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Mascara2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_LabtopRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_HostName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_LabtopRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_LabtopRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_RdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel_LabtopRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Guardar2)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Labtop-Add", jPanel_LabtopRemove);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel_ListLayout = new javax.swing.GroupLayout(jPanel_List);
        jPanel_List.setLayout(jPanel_ListLayout);
        jPanel_ListLayout.setHorizontalGroup(
            jPanel_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(397, Short.MAX_VALUE))
        );
        jPanel_ListLayout.setVerticalGroup(
            jPanel_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ListLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("List", jPanel_List);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel9.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel9.setText("Ingrese el Numero de la PC que desea Eliminar");

        jButtonRemove.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jButtonRemove.setText("Eliminar");
        jButtonRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRemoveMouseClicked(evt);
            }
        });
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_RemoveLayout = new javax.swing.GroupLayout(jPanel_Remove);
        jPanel_Remove.setLayout(jPanel_RemoveLayout);
        jPanel_RemoveLayout.setHorizontalGroup(
            jPanel_RemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RemoveLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 400, Short.MAX_VALUE))
            .addGroup(jPanel_RemoveLayout.createSequentialGroup()
                .addGroup(jPanel_RemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_RemoveLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_RemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_RemoveLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jTextField_Quitar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel_RemoveLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_RemoveLayout.setVerticalGroup(
            jPanel_RemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RemoveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Quitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRemove)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Remove", jPanel_Remove);

        javax.swing.GroupLayout jFrame_CRUDLayout = new javax.swing.GroupLayout(jFrame_CRUD.getContentPane());
        jFrame_CRUD.getContentPane().setLayout(jFrame_CRUDLayout);
        jFrame_CRUDLayout.setHorizontalGroup(
            jFrame_CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_CRUDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jFrame_CRUDLayout.setVerticalGroup(
            jFrame_CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_CRUDLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel_Principal.setBackground(new java.awt.Color(51, 51, 255));
        jPanel_Principal.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Zapfino", 0, 24)); // NOI18N
        jLabel1.setText("Menu Principal");

        jButtonIngresar.setFont(new java.awt.Font("Zapfino", 0, 14)); // NOI18N
        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIngresarMouseClicked(evt);
            }
        });
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });

        jButtonCRUD.setFont(new java.awt.Font("Zapfino", 0, 14)); // NOI18N
        jButtonCRUD.setText("CRUD");
        jButtonCRUD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCRUD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCRUDMouseClicked(evt);
            }
        });
        jButtonCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCRUDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_PrincipalLayout = new javax.swing.GroupLayout(jPanel_Principal);
        jPanel_Principal.setLayout(jPanel_PrincipalLayout);
        jPanel_PrincipalLayout.setHorizontalGroup(
            jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PrincipalLayout.createSequentialGroup()
                .addGroup(jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_PrincipalLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addGroup(jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCRUD)))
                    .addGroup(jPanel_PrincipalLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel_PrincipalLayout.setVerticalGroup(
            jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PrincipalLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButtonCRUD)
                .addGap(38, 38, 38)
                .addComponent(jButtonIngresar)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jButtonCRUDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCRUDMouseClicked
        jFrame_CRUD.setVisible(true);
        jFrame_CRUD.setSize(500, 500);
    }//GEN-LAST:event_jButtonCRUDMouseClicked

    private void jTextField_IP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IP1ActionPerformed

    private void jTextField_HostName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_HostName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_HostName1ActionPerformed

    private void jButtonCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCRUDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCRUDActionPerformed

    private void jButton_Guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Guardar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Guardar1ActionPerformed

    private void jButton_Guardar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Guardar1MouseClicked
        // TODO add your handling code here:

        try {
            IP1 = jTextField_IP1.getText();
            mascara1 = jTextField_Mascara1.getText();
            hostName1 = jTextField_HostName1.getText();

            RAM = Integer.parseInt(jTextField_RAM.getText());
            capacidadAlmacenamiento = Integer.parseInt(jTextField_CdA.getText());
            tipoAlmacenamiento = jTextField_TdA.getText();

            if (jCheckBox1.isSelected()) {
                tarjetaGrafica = true;
            } else {
                tarjetaGrafica = false;
            }

            Escritorio escritorio = new Escritorio(RAM, capacidadAlmacenamiento, tipoAlmacenamiento, tarjetaGrafica, IP1, mascara1, hostName1);
            computadoras.add(escritorio);
            JOptionPane.showMessageDialog(null, "Se ha guardado con éxito");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }


    }//GEN-LAST:event_jButton_Guardar1MouseClicked

    private void jButton_Guardar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Guardar2MouseClicked
        // TODO add your handling code here:

        try {
            IP2 = jTextField_IP1.getText();
            mascara2 = jTextField_Mascara1.getText();
            hostName2 = jTextField_HostName1.getText();

            marca = jTextField_Marca.getText();
            resolucionP = jTextField_RdP.getText();

            if (jCheckBox2.isSelected()) {
                RGB = true;
            } else {
                RGB = false;
            }

            Laptob laptob = new Laptob(marca, resolucionP, RGB, IP2, mascara2, hostName2);
            computadoras.add(laptob);
            JOptionPane.showMessageDialog(null, "Se ha guardado con éxito");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }


    }//GEN-LAST:event_jButton_Guardar2MouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:

        String l = "";

        if (computadoras.isEmpty()) {
            l = "";
        } else {
            for (int i = 0; i < computadoras.size(); i++) {

                l += i + " " + "-" + " " + computadoras.get(i) + "\n";

                System.out.println(computadoras.get(i));

            }
        }

        jTextArea1.setText(l);
        jTextArea2.setText(l);

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jButtonRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemoveMouseClicked
        // TODO add your handling code here:

        try {
            n = Integer.parseInt(jTextField_Quitar.getText());

            computadoras.remove(n);
            JOptionPane.showMessageDialog(null, "Se ha eliminado con éxito");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }


    }//GEN-LAST:event_jButtonRemoveMouseClicked

    private void jButtonIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIngresarMouseClicked
        // TODO add your handling code here:
        setVisible(false);

        System.out.println("Elija un IP");
        String seleccion = "";
        int seleccion2 = 0;

        for (int i = 0; i < computadoras.size(); i++) {

            if (computadoras.get(i).getIP().equals(seleccion)) {
                seleccion2 = computadoras.indexOf(i);
            }
        }

        if (computadoras.isEmpty()) {
            System.out.println("Aun no hay Computadoras");
        } else {

            while (m != 1) {

                System.out.println("Ingrese una de las siguientes opciones: \n"
                        + "1. Show\n"
                        + "2. Ping\n"
                        + "3. Exit\n");

                int opcionUsuario = entrada.nextInt();

                switch (opcionUsuario) {

                    case 1:

                        System.out.println(computadoras.get(seleccion2).getIP());
                        System.out.println(computadoras.get(seleccion2).getIP());

                        break;

                    case 2:

                        System.out.println("Ingrese el IP al que desea hacer PING");
                        String seleccion3 = entrada.next();
                        seleccion3 += entrada.nextLine();

                        String mask1_string = "" + seleccion.charAt(seleccion.length() - 1);

                        int mask1 = Integer.parseInt(mask1_string);

                        Integer.toBinaryString(mask1);

                        String mask2_string = "" + seleccion3.charAt(seleccion3.length() - 1);

                        int mask2 = Integer.parseInt(mask2_string);

                        int seleccion4 = 0;

                        for (int i = 0; i < computadoras.size(); i++) {

                            if (computadoras.get(i).getIP().equals(seleccion)) {
                                seleccion4 = computadoras.indexOf(i);
                            }
                            
                        }

                            if (mask1 == mask2) {

                                System.out.println(computadoras.get(seleccion2).getHostName() + " #" + computadoras.get(seleccion2).getIP()
                                + "Pinging to " + computadoras.get(seleccion4).getIP() +"\n" + "Reply from " + computadoras.get(seleccion2).getIP() + " bytes = 32 time = 37ms + TTL = 46"
                                + "Reply from " + computadoras.get(seleccion2).getIP() + " bytes = 32 time = 37ms + TTL = 46" +
                                        "Reply from " + computadoras.get(seleccion2).getIP() + " bytes = 32 time = 37ms + TTL = 46" +
                                        "Reply from " + computadoras.get(seleccion2).getIP() + " bytes = 32 time = 37ms + TTL = 46 \n" +
                                        "Ping statics for " + computadoras.get(seleccion2).getIP() + ":\n" + "      Packets: sent = 4, Received = 4, Lost = 0 (0% loss\n" +
                                        computadoras.get(seleccion2).getHostName());

                            } else if (mask1 != mask2) {
                                
                                System.out.println(computadoras.get(seleccion2).getHostName() + " #" + computadoras.get(seleccion2).getIP()
                                + "Pinging to " + computadoras.get(seleccion4).getIP() +"\n" + "Request time out\n" + "Destination host unreachable\n" +"Destination host unreachable\n" + "Destination host unreachable\n"+ "Destination host unreachable\n"+
                                        "Ping statics for " + computadoras.get(seleccion2).getIP() + ":\n" + "      Packets: sent = 4, Received = 4, Lost = 0 (0% loss\n" +
                                        computadoras.get(seleccion2).getHostName());
                                
                                
                            } else{
                                
                                System.out.println(computadoras.get(seleccion2).getHostName() + " #" + computadoras.get(seleccion2).getIP()
                                + "Pinging to " + computadoras.get(seleccion4).getIP() +"\n" + "Request time out\n" + "Request time out\n" +"Request time out\n" + "Request time out\n"+ "Request time out\n"+
                                        "Ping statics for " + computadoras.get(seleccion2).getIP() + ":\n" + "      Packets: sent = 4, Received = 4, Lost = 0 (0% loss\n" +
                                        computadoras.get(seleccion2).getHostName());
                                
                            }
                            

                            break;

                        
                
            
        case 3:
                    
                    setVisible(true);
                    m++;
                    break;
                    
                default:
                    System.out.println("Opción no valida");
                    break;
            }

        }
        }
        
        
        


    }//GEN-LAST:event_jButtonIngresarMouseClicked

    /**
     * @param args the command line arguments
     */
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonCRUD;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JButton jButton_Guardar1;
    private javax.swing.JButton jButton_Guardar2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JFrame jFrame_CRUD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_IP2;
    private javax.swing.JPanel jPanel_LabtopRemove;
    private javax.swing.JPanel jPanel_List;
    private javax.swing.JPanel jPanel_PCadd;
    private javax.swing.JPanel jPanel_Principal;
    private javax.swing.JPanel jPanel_Remove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField_CdA;
    private javax.swing.JTextField jTextField_HostName1;
    private javax.swing.JTextField jTextField_HostName2;
    private javax.swing.JTextField jTextField_IP1;
    private javax.swing.JTextField jTextField_IP2;
    private javax.swing.JTextField jTextField_Marca;
    private javax.swing.JTextField jTextField_Mascara1;
    private javax.swing.JTextField jTextField_Mascara2;
    private javax.swing.JTextField jTextField_Quitar;
    private javax.swing.JTextField jTextField_RAM;
    private javax.swing.JTextField jTextField_RdP;
    private javax.swing.JTextField jTextField_TdA;
    // End of variables declaration//GEN-END:variables

    //Mis Variables
    Scanner entrada = new Scanner(System.in);

    ArrayList<PC> computadoras = new ArrayList();

    int n;
    int m;

    // Variables PC-Escritorio
    String IP1;
    String mascara1;
    String hostName1;
    int RAM;
    int capacidadAlmacenamiento;
    String tipoAlmacenamiento;
    boolean tarjetaGrafica;

    // Variables Labtop
    String IP2;
    String mascara2;
    String hostName2;
    String marca;
    String resolucionP;
    boolean RGB;

}
